import { DemoClient, DemoCustomer, ClientTemplate } from "./types";

/**
 * ==========================================================
 * Client Templates
 * ----------------------------------------------------------
 * Source: CLIENT_BIBLE.md
 *
 * These represent the company's real client portfolio.
 * They NEVER change between runs.
 * ==========================================================
 */

const CLIENT_TEMPLATES: ClientTemplate[] = [
  {
    companyName: "Pinnacle Degree College",
    category: "College",
    city: "Hyderabad",
    contactName: "Dr. Ramesh Kumar",
    email: "finance@pinnacledegreecollege.edu.in",
    phone: "9876501001",
    gstNumber: "36ABCDE1234F1Z5",
    paymentProfile: "Reliable",
    paymentTerms: 30,
    averageInvoice: 180000,
    trustScore: 92,
  },
  {
    companyName: "Horizon Business School",
    category: "College",
    city: "Hyderabad",
    contactName: "Priya Sharma",
    email: "accounts@horizonbusinessschool.edu.in",
    phone: "9876501002",
    gstNumber: "36ABCDE1234F1Z6",
    paymentProfile: "Delayed",
    paymentTerms: 30,
    averageInvoice: 220000,
    trustScore: 83,
  },
  {
    companyName: "Vertex Consulting Pvt. Ltd.",
    category: "Corporate",
    city: "Bengaluru",
    contactName: "Arjun Mehta",
    email: "finance@vertexconsulting.in",
    phone: "9876501003",
    gstNumber: "29ABCDE1234F1Z7",
    paymentProfile: "Premium",
    paymentTerms: 15,
    averageInvoice: 325000,
    trustScore: 98,
  },
  {
    companyName: "BluePeak Technologies",
    category: "Corporate",
    city: "Hyderabad",
    contactName: "Sneha Reddy",
    email: "accounts@bluepeaktech.in",
    phone: "9876501004",
    gstNumber: "36ABCDE1234F1Z8",
    paymentProfile: "Enterprise",
    paymentTerms: 45,
    averageInvoice: 280000,
    trustScore: 90,
  },
  {
    companyName: "SkillForge Learning",
    category: "Training Partner",
    city: "Mumbai",
    contactName: "Karan Joshi",
    email: "finance@skillforgelearning.in",
    phone: "9876501005",
    gstNumber: "27ABCDE1234F1Z9",
    paymentProfile: "Reliable",
    paymentTerms: 30,
    averageInvoice: 125000,
    trustScore: 95,
  },
  {
    companyName: "FutureBridge Academy",
    category: "Training Partner",
    city: "Pune",
    contactName: "Neha Kulkarni",
    email: "accounts@futurebridge.in",
    phone: "9876501006",
    gstNumber: "27ABCDE1234F2Z1",
    paymentProfile: "Reliable",
    paymentTerms: 30,
    averageInvoice: 140000,
    trustScore: 94,
  },
  {
    companyName: "Apex Engineering College",
    category: "College",
    city: "Hyderabad",
    contactName: "Dr. Srinivas Rao",
    email: "finance@apexengg.edu.in",
    phone: "9876501007",
    gstNumber: "36ABCDE1234F2Z2",
    paymentProfile: "Reliable",
    paymentTerms: 30,
    averageInvoice: 240000,
    trustScore: 91,
  },
  {
    companyName: "Sunrise Degree College",
    category: "College",
    city: "Warangal",
    contactName: "Lakshmi Devi",
    email: "accounts@sunrisedegree.edu.in",
    phone: "9876501008",
    gstNumber: "36ABCDE1234F2Z3",
    paymentProfile: "Slow",
    paymentTerms: 30,
    averageInvoice: 145000,
    trustScore: 68,
  },
  {
    companyName: "Silver Oak Institute",
    category: "College",
    city: "Hyderabad",
    contactName: "Harish Kumar",
    email: "finance@silveroak.edu.in",
    phone: "9876501009",
    gstNumber: "36ABCDE1234F2Z4",
    paymentProfile: "Premium",
    paymentTerms: 15,
    averageInvoice: 95000,
    trustScore: 98,
  },
  {
    companyName: "Greenfield Women's College",
    category: "College",
    city: "Vijayawada",
    contactName: "Sujatha Rao",
    email: "accounts@greenfieldwc.edu.in",
    phone: "9876501010",
    gstNumber: "37ABCDE1234F2Z5",
    paymentProfile: "Reliable",
    paymentTerms: 30,
    averageInvoice: 160000,
    trustScore: 90,
  },
  {
    companyName: "Eastern State University",
    category: "University",
    city: "Visakhapatnam",
    contactName: "Prof. Mahesh Varma",
    email: "finance@esu.ac.in",
    phone: "9876501011",
    gstNumber: "37ABCDE1234F2Z6",
    paymentProfile: "Enterprise",
    paymentTerms: 45,
    averageInvoice: 360000,
    trustScore: 88,
  },
  {
    companyName: "Global Tech University",
    category: "University",
    city: "Bengaluru",
    contactName: "Dr. Anjali Nair",
    email: "accounts@gtu.ac.in",
    phone: "9876501012",
    gstNumber: "29ABCDE1234F2Z7",
    paymentProfile: "Reliable",
    paymentTerms: 30,
    averageInvoice: 295000,
    trustScore: 93,
  },
  {
    companyName: "Quantum Systems Pvt. Ltd.",
    category: "Corporate",
    city: "Hyderabad",
    contactName: "Rohit Verma",
    email: "finance@quantumsystems.in",
    phone: "9876501013",
    gstNumber: "36ABCDE1234F2Z8",
    paymentProfile: "Reliable",
    paymentTerms: 30,
    averageInvoice: 270000,
    trustScore: 89,
  },
  {
    companyName: "Nova Manufacturing Pvt. Ltd.",
    category: "Corporate",
    city: "Chennai",
    contactName: "Vikram Iyer",
    email: "accounts@novamfg.in",
    phone: "9876501014",
    gstNumber: "33ABCDE1234F2Z9",
    paymentProfile: "Slow",
    paymentTerms: 45,
    averageInvoice: 390000,
    trustScore: 66,
  },
  {
    companyName: "Stellar Analytics Pvt. Ltd.",
    category: "Corporate",
    city: "Hyderabad",
    contactName: "Nikhil Gupta",
    email: "finance@stellaranalytics.in",
    phone: "9876501015",
    gstNumber: "36ABCDE1234F3Z1",
    paymentProfile: "Premium",
    paymentTerms: 15,
    averageInvoice: 230000,
    trustScore: 99,
  },
  {
    companyName: "Delta Logistics Ltd.",
    category: "Corporate",
    city: "Mumbai",
    contactName: "Amit Deshmukh",
    email: "accounts@deltalogistics.in",
    phone: "9876501016",
    gstNumber: "27ABCDE1234F3Z2",
    paymentProfile: "Delayed",
    paymentTerms: 45,
    averageInvoice: 280000,
    trustScore: 79,
  },
  {
    companyName: "Precision Components Pvt. Ltd.",
    category: "Corporate",
    city: "Pune",
    contactName: "Sandeep Patil",
    email: "finance@precisioncomponents.in",
    phone: "9876501017",
    gstNumber: "27ABCDE1234F3Z3",
    paymentProfile: "Enterprise",
    paymentTerms: 45,
    averageInvoice: 420000,
    trustScore: 86,
  },
  {
    companyName: "Zenith Healthcare Pvt. Ltd.",
    category: "Corporate",
    city: "Hyderabad",
    contactName: "Meera Nair",
    email: "accounts@zenithhealthcare.in",
    phone: "9876501018",
    gstNumber: "36ABCDE1234F3Z4",
    paymentProfile: "Reliable",
    paymentTerms: 30,
    averageInvoice: 210000,
    trustScore: 92,
  },
  {
    companyName: "LaunchPad Startups",
    category: "Startup",
    city: "Hyderabad",
    contactName: "Rahul Chandra",
    email: "finance@launchpadstartups.in",
    phone: "9876501019",
    gstNumber: "36ABCDE1234F3Z5",
    paymentProfile: "Reliable",
    paymentTerms: 15,
    averageInvoice: 75000,
    trustScore: 93,
  },
  {
    companyName: "Telangana Skill Mission",
    category: "Government",
    city: "Hyderabad",
    contactName: "R. Prasad",
    email: "accounts@tsm.gov.in",
    phone: "9876501020",
    gstNumber: "36ABCDE1234F3Z6",
    paymentProfile: "High Risk",
    paymentTerms: 60,
    averageInvoice: 550000,
    trustScore: 72,
  },
  {
    companyName: "Crestview Commerce College",
    category: "College",
    city: "Hyderabad",
    contactName: "Pooja Reddy",
    email: "finance@crestview.edu.in",
    phone: "9876501021",
    gstNumber: "36ABCDE1234F3Z7",
    paymentProfile: "Delayed",
    paymentTerms: 30,
    averageInvoice: 155000,
    trustScore: 81,
  },
  {
    companyName: "Future Minds College",
    category: "College",
    city: "Karimnagar",
    contactName: "K. Srinivas",
    email: "accounts@futureminds.edu.in",
    phone: "9876501022",
    gstNumber: "36ABCDE1234F3Z8",
    paymentProfile: "Slow",
    paymentTerms: 30,
    averageInvoice: 120000,
    trustScore: 69,
  },
  {
    companyName: "NextGen Learning Solutions",
    category: "Training Partner",
    city: "Bengaluru",
    contactName: "Deepika Menon",
    email: "finance@nextgenlearning.in",
    phone: "9876501023",
    gstNumber: "29ABCDE1234F3Z9",
    paymentProfile: "Reliable",
    paymentTerms: 30,
    averageInvoice: 165000,
    trustScore: 95,
  },
  {
    companyName: "Pioneer Auto Components",
    category: "Corporate",
    city: "Chennai",
    contactName: "Suresh Babu",
    email: "accounts@pioneerauto.in",
    phone: "9876501024",
    gstNumber: "33ABCDE1234F4Z1",
    paymentProfile: "Enterprise",
    paymentTerms: 45,
    averageInvoice: 340000,
    trustScore: 84,
  },
  {
    companyName: "BlueRiver Consulting",
    category: "Corporate",
    city: "Hyderabad",
    contactName: "Anita Kapoor",
    email: "finance@blueriverconsulting.in",
    phone: "9876501025",
    gstNumber: "36ABCDE1234F4Z2",
    paymentProfile: "Premium",
    paymentTerms: 30,
    averageInvoice: 220000,
    trustScore: 97,
  },
];

export function generateClients(): DemoClient[] {
  return CLIENT_TEMPLATES.map((client) => {
    const customer: DemoCustomer = {
      id: crypto.randomUUID(),

      company_name: client.companyName,

      contact_name: client.contactName,

      email: client.email,

      phone: client.phone,

      gst_number: client.gstNumber,

      status: "active",

      created_at: new Date("2026-05-01"),

      updated_at: new Date("2026-08-04"),

      external_customer_id: null,
    };

    return {
      customer,
      profile: client,
    };
  });
}

export { CLIENT_TEMPLATES };